<a href="https://colab.research.google.com/github/JoelAlgera/Deep-Learning-Practice/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

In [2]:
import numpy as np

# Numpy Arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.6993071 , 0.75030734, 0.87102756, 0.75691084],
       [0.5028056 , 0.88995648, 0.90983014, 0.02587204],
       [0.62678518, 0.1371645 , 0.42794464, 0.9493351 ]])

In [5]:
np1.dtype

dtype('float64')

# Tensor


In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8764,  0.1187, -1.5711,  0.5868],
        [-0.9700,  0.7308,  0.0365,  0.7140],
        [ 0.0370,  1.7332,  0.4411, -0.3112]])

In [9]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6993, 0.7503, 0.8710, 0.7569],
        [0.5028, 0.8900, 0.9098, 0.0259],
        [0.6268, 0.1372, 0.4279, 0.9493]], dtype=torch.float64)

# Tensor Operations

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Reshape if we don't know the number of items
my_torch2 = torch.arange(15)

my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
my_torch3 = torch.arange(10)

my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
#reshape and view will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices


In [28]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#grab a specific item
my_torch7[7]

tensor(7)

In [30]:
#grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [32]:
#Return Column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])