<a href="https://colab.research.google.com/github/JoelAlgera/Deep-Learning-Practice/blob/main/TensorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Tensor Math Operations


In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
#Sub Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
#multiplication longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
 #modulus
 tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
#mod longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [19]:
#Exponents/power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [20]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [22]:
#ALTERNATE SYNTAX
tensor_a.add(tensor_b)
tensor_a.sub(tensor_b)
tensor_a.mul(tensor_b)
#etc

tensor([ 5, 12, 21, 32])

In [24]:
#Reassignement_ (setting the tensor as the result)
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])